---
- name: use vhost role playbook
  hosts: ansible1.example.com
  pre_tasks:
    - name: pre tasks message
      debug:
        msg: "Ensure web server configuration"
  roles:
    - myvhost
  post_tasks:
    - name: HTML content is install
      copy:
        src: files/html/
        dest: /var/www/vhost/{{ ansible_hostname }}
    - name: post_tasks message
      debug:
        msg: 'Web server is configured'
